[theme]
primaryColor = "#4F46E5"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#EEF2FF"
textColor = "#1E293B"
 font="Nunito:https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000, sans-serif"
 codeFont="'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap, monospace"